# Generated by Django 5.1.6 on 2025-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Phone', models.CharField(max_length=255, unique=True, verbose_name='شماره تلفن')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('verification_time', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='پروفایل')),
                ('Authentication', models.BooleanField(default=False, verbose_name='وضعیت احراز هویت')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
