# Generated by Django 5.1.6 on 2025-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
