# Generated by Django 4.2 on 2024-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=7, default=1.0, max_digits=12, verbose_name='تعداد'),
        ),
    ]
