# Generated by Django 4.2 on 2024-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام محصول'),
        ),
    ]
