# Generated by Django 4.2 on 2024-08-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_maincategory_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'عدد'), (2, 'کیلو')], default=1, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=7, default=1.0, max_digits=12, verbose_name='تعداد'),
        ),
    ]
