# Generated by Django 4.2 on 2024-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_unit_type_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='کد محصول'),
        ),
    ]
